build: false

environment:
    CONAN_CHANNEL: "stable"

    PYTHON: "C:\\Python37"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CONAN_VISUAL_VERSIONS: 16

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip3 install conan --upgrade
  - pip3 install conan_package_tools bincrafters_package_tools
  - conan user # It creates the conan data directory

test_script:
  - "%PYTHON%/python.exe .ci/build.py"
